# Before running brew bundle run brew tap Homebrew/bundle
#https://github.com/Homebrew/homebrew-bundle
tap "caskroom/cask"
tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/core"
tap "neovim/neovim"
brew "ruby"
brew "python"
brew "ansible"
brew "ansible-lint"
brew "git"
brew "docker"
brew "neovim"
brew "pass"
brew "tmux"
brew "fzf"
brew "wget"
cask "font-hack"
cask "minikube"
cask "vagrant"
cask "virtualbox"
cask "iterm2"
